### ISSUE TITLE
timezone adjustment of time-axes

### ISSUE THREAD

**Issue by mojoaxel** [asdil12/fff-monitoring#11]
It looks like the time-axes are in GMT. Other times are in the correct "frankonian timezone" ;-)
e.g. 13:00 should be 14:00.

**Comment by asdil12** [comment]
I know - but I don't know how to fix it.
The js lib timezone doesn't seem to have any effect.

**Comment by mojoaxel** [comment]
I'll have a look

**Comment by mojoaxel** [comment]
As far as I can see you need to provide timezone-config files. In the [flot-example](http://www.flotcharts.org/flot/examples/axes-time-zones/) they are in a folder "tz". You can download files like "europe", "asia" or "northamerica" e.g. from the [IETF](https://www.ietf.org/timezones/data/).

In addition you need to configure timezoneJS in your `graph.js` :
```javascript
timezoneJS.timezone.zoneFileBasePath = "tz";
timezoneJS.timezone.defaultZoneFile = [];
timezoneJS.timezone.init({async: false});
```
Something like that...

**Comment by asdil12** [comment]
http://api.mongodb.org/python/current/examples/datetimes.html

The problem is, that the datetime objects that are stored in the database are - despite representing utc time - naive datatypes that do not know their timezone (they actuall y can know the timezone if it is set).

Even if the tzinfo is set when saving the time object it won't be set when reading the object from the database.

There is a way to let mongodb set the tzinfo property when reading objects by setting `tz_aware=True`.

The timezone-aware datetime object is needed, because the function, that converts the datetime object into a javascript timestamp (milliseconds since epoch) simply calls the `.timestamp()` method of the datetime object.
Since python 3.3 this method assumes, that the datetime object is in local time and not in UTC, if no tzinfo is set (i.e. it is naive). Then the JS timestamp is UTC-1 (as CET is UTC+1 in winter) but UTC is assumed. (see https://docs.python.org/3.3/library/datetime.html#datetime.datetime.timestamp

**Comment by mojoaxel** [comment]
thanks :-)
